# Generated by Django 3.0.3 on 2020-03-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_featured_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='featured_picture',
            new_name='featured_image',
        ),
    ]
