# Generated by Django 3.0.4 on 2020-03-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200317_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
